### ISSUE TITLE
README is not clear enough about the installation steps

### ISSUE THREAD

**Issue by vinogradoff** [amolenaar/fitnesse-maven-classpath#11]
Hey, guy!

> How to use.
> Download the distribution.
> Get yourself an up-to-date copy of fitnesse (>= 20150114)

Okay, I've downloaded it, but where should I put the files to make it work? :)
It seems just downloading is not enough.

Thank you!

**Comment by amolenaar** [comment]
Hi,

You can add the dependency to your Maven pom.xml file. https://github.com/xebia/Xebium contains a nice example for that.

Regards,

Arjan

**Comment by vinogradoff** [comment]
I wish I could start fitnesse as standalone from command-line using java only (no maven).

I've got maven-classpath-plugin-1.9.jar from maven-repo and try to start with:

```
java -cp maven-classpath-plugin-1.9.jar -jar fitness-standalone -d ./fitness 
```

./fitness/plugins.properties has the line 

```
SymbolTypes = fitnesse.wikitext.widgets.MavenClasspathSymbolType
```

added.

After start I've got

```
$ java -cp *maven*.jar -jar fitnesse-standalone.jar  -d ./fitnesse -p 8088 -o
fitnesse.plugins.PluginException: Unable to load class fitnesse.wikitext.widgets.MavenClasspathSymbolType
    at fitnesse.plugins.PropertyBasedPluginFeatureFactory.forName(PropertyBasedPluginFeatureFactory.java:200)
    at fitnesse.plugins.PropertyBasedPluginFeatureFactory.forEachClass(PropertyBasedPluginFeatureFactory.java:143)
    at fitnesse.plugins.PropertyBasedPluginFeatureFactory.forEachObject(PropertyBasedPluginFeatureFactory.java:150)
    at fitnesse.plugins.PropertyBasedPluginFeatureFactory.registerSymbolTypes(PropertyBasedPluginFeatureFactory.java:75)
    at fitnesse.plugins.PluginsLoader.loadSymbolTypes(PluginsLoader.java:83)
    at fitnesse.ContextConfigurator.makeFitNesseContext(ContextConfigurator.java:151)
    at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:65)
    at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:54)
    at fitnesseMain.FitNesseMain.main(FitNesseMain.java:34)
Caused by: java.lang.ClassNotFoundException:  fitnesse.wikitext.widgets.MavenClasspathSymbolType
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at fitnesse.plugins.PropertyBasedPluginFeatureFactory.forName(PropertyBasedPluginFeatureFactory.java:198)
    ... 8 more
```

What goes wrong?

**Comment by aquddos123** [comment]
Hi Arjan, 

I'm also encountering an Exception using this method. I configured my project based on  https://github.com/xebia/Xebium ([blog ](http://blog.xebia.com/fitnesse-and-dependency-management-with-maven/)) and have been using it for the last two years.

Currently, I'm using FitNesse version 20140630 and am trying to upgrade to 20151230. I'm able to bring up new FitNesse instance through maven but when I try to add `!pomFile pom.xml` to the "root" page and save it like it use to be before it throws the following on page Exception:

`org.apache.velocity.exception.MethodInvocationException: Invocation of method 'render' in  class fitnesse.responders.WikiPageResponder$WikiPageRenderer threw exception java.lang.AbstractMethodError at wikiPage.vm[line 1, column 10]
`
My `plugin.properties` and `POM` both resides in the same folder. And I'm using maven-classpath-plugin version 1.7. Any idea how to get around this issue? 

Any help is much appreciated in advance. Thanks!!
